excerpt_separator:""
pygments:true
markdown:kramdown
url:"http://bukodi.github.io"
title:"Bukodi László"
tagline:"A log of everyday life"
description:"My awesome new site"
paginate:20

theme: jekyll-theme-hacker